### ISSUE TITLE
Crosshair events don't trigger

### ISSUE THREAD

**Issue by tbuteler** [f5/unovis#317]
I can't seem to get Crosshair events to trigger, though I'm not sure if I'm missing something.

```vue
<script>
// ...
const events = {
  [Crosshair.selectors.circle]: {
    mouseover: (data) => console.log(data),
    click: (data) => console.log(data),
  },
  [Crosshair.selectors.line]: {
    mouseover: (data) => console.log(data),
    click: (data) => console.log(data),
  },
};
</script>

<template>
  <VisXYContainer :data="data" :height="height">
    <VisStackedBar :x="x" :y="y" />
    <VisCrosshair :events="events" />
    <VisAxis type="x" />
  </VisXYContainer>
</template>
```

I cloned an example from the gallery which used a crosshair and tried it there, without success: https://stackblitz.com/edit/lats1u?file=src%2FApp.vue

I'm hoping an event in the crosshair's circle will give me that point's specific data in an area chart, as the tooltip component will receive all series in my chart, and that will usually be too much data to render at once. If there's a better way to do this, I'd love to understand it better.

**Comment by rokotyan** [comment]
@tbuteler You're right, Crosshair is "invisible" for events because it's an auxiliary component.

But if you want to use it with Tooltip, Crosshair knows how to handle that: if you provide a `template` function, Crosshair will pass the individual data points there.

Here's a documentation section about that: https://unovis.dev/docs/auxiliary/Crosshair#displaying-custom-content.

And a gallery example: https://unovis.dev/gallery/view?collection=%20Auxiliary%20Components&title=Stacked%20Bar%20Chart%20with%20Crosshair

**Comment by tbuteler** [comment]
@rokotyan thanks for your reply. I should've perhaps clarified that I have a stacked area chart, and in some circumstances I will have too many areas stacked, which makes it a bit impractical to show on one tooltip.

I created a contrived example to show what I mean; at some point the length of items within the tooltip is large enough that it becomes jittery when recomputing the tooltip location: https://stackblitz.com/edit/n5vnx9?file=src%2FApp.vue

So I had wondered if I could use events on the crosshair to understand which point the user was hovering over and showing a tooltip for that point only, which would make the tooltip less cluttered and solve the jitter. Alternatively, I'd add the tooltip on `mouseover` for `Area.selectors.area`, but then I don't have the information on the value of the current/nearest X axis tick being hovered, but rather the entire series.

But I understand if all this is too specific and out of scope, so feel free to close this issue if there are no alternatives.

**Comment by rokotyan** [comment]
Thanks for explaining the problem @tbuteler!

You can solve the jitter problem by setting tooltip's [`container`](https://unovis.dev/docs/auxiliary/Tooltip#container) to `document.body`, i.e.: 
<img width="411" alt="image" src="https://github.com/f5/unovis/assets/755708/f2093daa-3bb1-4b3f-bf49-97c68d352ea2">

Unfortunately we don't have a mechanism for providing individual data points when hovering over Area or Line components because they are continuously rendered using numbers from the whole data array. You can, however, render a Scatter component on top of your Area and set up events for corresponding data points. Will that solve your problem?

**Comment by tbuteler** [comment]
@rokotyan yes, either solution should be enough for my needs. Thank you so much for your help, and for sharing this library with us!

**Comment by rokotyan** [comment]
@tbuteler You are welcome!
